Application/Web/EveryDayBlog.Web/Areas/Administration/Controllers/UsersRequestsController.cs
namespace EveryDayBlog.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using EveryDayBlog.Services.Data;
    using EveryDayBlog.Web.Areas.Administration.ViewModels.Messages.ViewModel;
    using EveryDayBlog.Web.ViewModels.Images.ViewModels;
    using EveryDayBlog.Web.ViewModels.PageHeaders.ViewModels;
    using EveryDayBlog.Web.ViewModels.UsersRequests.ViewModels;
    using Microsoft.AspNetCore.Mvc;

    public class UsersRequestsController : AdminBaseController
    {
        private const string Url = @"mailto:viewModel.Email?subject=Re: viewModel.Name&body=%0D%0A%0D%0ARe: viewModel.Message""";
        private const string NonExistingMsgIdErrorMsg = "There is no message with that Id.";
        private readonly IUserRequestService userRequestService;
        private readonly IPageHeaderService pageHeaderService;

        public UsersRequestsController(
            IUserRequestService userRequestService,
            IPageHeaderService pageHeaderService)
        {
            this.userRequestService = userRequestService;
            this.pageHeaderService = pageHeaderService;
        }

        [HttpGet]
        public async Task<IActionResult> Messages()
        {
            var unreadedMessages = await this.userRequestService.TakeAllNonReadedRequests<UserRequestDetailsViewModel>();
            var readedMessages = await this.userRequestService.TakeAllReadedRequests<UserRequestDetailsViewModel>();

            var viewModel = new MessagesViewModel
            {
                PageHeader = new PageHeaderViewModel { Image = new ImageBackgroundViewModel { } },
                UserRequestDetailsReaded = readedMessages,
                UserRequestDetailsUnReaded = unreadedMessages,
            };

            return this.View(viewModel);
        }

        [HttpGet]
        public async Task<ActionResult> Readed(int id)
        {
            var isReadedSucceded = await this.userRequestService.MarkAsReadedAsync(id);
            if (isReadedSucceded == false)
            {
                this.TempData["alert"] = NonExistingMsgIdErrorMsg;
            }

            return this.RedirectToAction("Messages");
        }

        [HttpGet]
        public async Task<ActionResult> SoftDelete(int id)
        {
            var isDeletedSuccedded = await this.userRequestService.SoftDeleteAsync(id);

            if (isDeletedSuccedded == false)
            {
                this.TempData["alert"] = NonExistingMsgIdErrorMsg;
            }

            return this.RedirectToAction("Messages");
        }

        [HttpGet]
        public async Task<ActionResult> Answer(int id)
        {
            var viewModel = await this.userRequestService.TakeUserRequestById<UserRequestDetailsViewModel>(id);
            if (viewModel == null)
            {
                this.TempData["alert"] = NonExistingMsgIdErrorMsg;
                return this.RedirectToAction("Messages");
            }

            return this.Redirect(Url);
        }

        [HttpGet]
        public async Task<IActionResult> Deleted(DeletedMessagesViewModel deletedMessagesViewModel = null)
        {
            if (deletedMessagesViewModel == null)
            {
                var deletedMessages = await this.userRequestService.TakeAllDeletedRequests<UserRequestDetailsViewModel>();

                deletedMessagesViewModel = new DeletedMessagesViewModel
                {
                    PageHeader = new PageHeaderViewModel { Image = new ImageBackgroundViewModel { } },
                    DeletedMessages = deletedMessages,
                };
            }
            else if (deletedMessagesViewModel.DeletedMessages == null || deletedMessagesViewModel.DeletedMessages.Count == 0)
            {
                if (await this.userRequestService.AnyDeletedUserRequests())
                {
                    var deletedMessages = await this.userRequestService.TakeAllDeletedRequests<UserRequestDetailsViewModel>();
                    deletedMessagesViewModel.DeletedMessages = deletedMessages;
                }
            }

            return this.View(deletedMessagesViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Deleted(int id)
        {
            await this.userRequestService.HardDeleteAsync(id);

            var deletedMessages = await this.userRequestService.TakeAllDeletedRequests<UserRequestDetailsViewModel>();
            var viewModel = new DeletedMessagesViewModel
            {
                PageHeader = new PageHeaderViewModel { Image = new ImageBackgroundViewModel { } },
                DeletedMessages = deletedMessages,
            };
            return this.View(viewModel);
        }
    }
}

Application/Web/EveryDayBlog.Web/Controllers/PostsController.cs
namespace EveryDayBlog.Web.Controllers
{
    using System.Threading.Tasks;

    using EveryDayBlog.Services;
    using EveryDayBlog.Services.Data;
    using EveryDayBlog.Web.ViewModels.Posts.InputModels;
    using EveryDayBlog.Web.ViewModels.Posts.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    [Authorize]
    public class PostsController : BaseController
    {
        private const string CreatingPostErrorMsg = "Something went wrong! We'll look at the problem and soon if all is well, your post will be uploaded!";
        private const string CreatingPostErrorLogMsg = "Post cannot be saved in the database.";
        private readonly IPostService postService;
        private readonly ILogger<PostsController> logger;
        private readonly IProtectionService protectionService;

        public PostsController(
            IPostService postService,
            ILogger<PostsController> logger,
            IProtectionService protectionService)
        {
            this.postService = postService;
            this.logger = logger;
            this.protectionService = protectionService;
        }

        [HttpGet]
        public IActionResult Create() => this.View();

        [HttpPost]
        public async Task<IActionResult> Create(PostInputModel post)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var isPostCreated = await this.postService.CreatePostAsync(post, this.User.Identity.Name);

            if (!isPostCreated)
            {
                this.TempData["alert"] = CreatingPostErrorMsg;
                this.logger.LogError(CreatingPostErrorLogMsg);
            }

            return this.Redirect("/");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            this.TempData["ProductId"] = id;

            var post = await this.postService.GetPostByIdAsync<IndexPostViewModel>(id);
            if (post == null)
            {
                return this.NotFound();
            }

            return this.View(post);
        }
    }
}

Application/Web/EveryDayBlog.Web/Controllers/SectionsController.cs
namespace EveryDayBlog.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using EveryDayBlog.Data.Models;
    using EveryDayBlog.Services.Data;
    using EveryDayBlog.Web.ViewModels.Posts.ViewModels;
    using EveryDayBlog.Web.ViewModels.Sections.InputModels;
    using EveryDayBlog.Web.ViewModels.Sections.ViewModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;

    [Authorize]
    public class SectionsController : BaseController
    {
        private const string SectionErrorMsg = "Your section wasn't added ,because of input errors!";
        private const string SectionAddErrorMsg = "Something went wrong! We'll look at the problem and soon if all is well, your section will be added!";

        private readonly ISectionService sectionService;
        private readonly ILogger<SectionsController> logger;

        public SectionsController(
            ISectionService sectionService,
            ILogger<SectionsController> logger)
        {
            this.sectionService = sectionService;
            this.logger = logger;
        }

        [HttpPost]
        public async Task<IActionResult> Add(SectionInputModel sectionInputModel)
        {
            var id = int.Parse(this.TempData["ProductId"].ToString());

            if (!this.ModelState.IsValid)
            {
                this.TempData["alert"] = SectionErrorMsg;
                return this.RedirectToAction("Details", "Posts", new { id = id });
            }

            var sectionId = await this.sectionService.CreateSectionAsync(sectionInputModel, id);

            if (sectionId != 0)
            {
                return this.RedirectToAction("Details", "Posts", new { id = id });
            }

            this.TempData["alert"] = SectionAddErrorMsg;
            this.logger.LogError(message: $"The section cannot be saved in the database <-----> postId -> {id}.");

            return this.RedirectToAction("Details", "Posts", new { id = id });
        }

        // GET: Sections
        public ActionResult Index()
        {
            return this.View();
        }

        // GET: Sections/Details/5
        public ActionResult Details(int id)
        {
            return this.View();
        }

        // GET: Sections/Create
        public ActionResult Create()
        {
            return this.View();
        }

        // POST: Sections/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return this.RedirectToAction(nameof(this.Index));
            }
            catch
            {
                return this.View();
            }
        }

        public ActionResult Delete(int id)
        {
            return this.View();
        }

        // POST: Sections/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return this.RedirectToAction(nameof(this.Index));
            }
            catch
            {
                return this.View();
            }
        }
    }
}

Application/Web/EveryDayBlog.Web/Areas/Administration/Views/Shared/Components/AdminNavbarComponent/Default.cshtml
@using EveryDayBlog.Web.ViewModels.AdminNavbars.ViewModels;
@model AdminNavbarViewModel

<style>
    .dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #3b5998;
    min-width: 300px;
    z-index: 1;
}

    .dropdown-content a {
        color: white;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }

        .dropdown-content a:hover {
            background-color: #47b7e9;
        }

.dropdown:hover .dropdown-content {
    display: block;
}

.dropdown:hover .dropbtn {
    background-color: #3b5998;
}

.navbar-nav li:hover > ul.dropdown-menu {
    display: block;
}

.navbar-nav li:hover > div.dropdown-menu {
    display: block;
}

.dropdown-submenu {
    position: relative;
}

    .dropdown-submenu > .dropdown-menu {
        top: 0;
        left: 100%;
        margin-top: -6px;
    }
</style>

<nav class="navbar navbar-expand-lg navbar-light py-0">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-envelope"></i>
                    @if (Model.UnReadedRequests != 0)
                    {
                        <sup>@Model.UnReadedRequests</sup>
                    }
                    User's messages
                </a>
                <ul class="dropdown-menu">
                    <li class="dropdown-item dropdown-submenu px-1 py-0">
                        <a asp-area="Administration" asp-controller="UsersRequests" asp-action="Messages" class="dropdown-item nav-link">
                            Messages
                            @if (Model.UnReadedRequests != 0)
                            {
                                <sup class="font-weight-bold text-danger">@Model.UnReadedRequests</sup>
                            }
                        </a>
                    </li>
                    <li class="dropdown-item dropdown-submenu px-1 py-0">
                        <a asp-area="Administration" asp-controller="UsersRequests" asp-action="Deleted" class="dropdown-item nav-link">Bin</a>
                    </li>
                    
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle font-weight-bold" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Posts
                </a>
                <ul class="dropdown-menu">
                    <li class="dropdown-item dropdown-submenu px-1 py-0">
                        <a href="#" class="dropdown-item nav-link dropdown-toggle">User's Posts</a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-item px-1 py-0">
                                <a asp-area="Administration" asp-controller="Home" asp-action="Index" class="dropdown-item nav-link">See all</a>
                            </li>
                            <li class="dropdown-item px-1 py-0">
                                <a asp-area="Administration" asp-controller="Sections" asp-action="Deleted" class="dropdown-item nav-link">Bin</a>
                            </li>
                        </ul>
                    </li>
                     <li class="dropdown-item dropdown-submenu px-1 py-0">
                        <a asp-area="Administration" asp-controller="Posts" asp-action="Hidden" class="dropdown-item nav-link">Bin</a>
                    </li>
                </ul>
            </li>
           
        </ul>
    </div>
</nav>
<hr class="my-1 hr-xeon d-none d-lg-block" />